### ISSUE TITLE
Dilithium Crystals example uses :db.install/_attribute :db.part/db

### ISSUE THREAD

**Issue by MageMasher** [cognitect-labs/day-of-datomic-cloud#5]
The Dilithium Crystals example uses `:db.install/_attribute :db.part/db` in it's schema definition.

While this doesn't cause an error, it is confusing since it's not required in datomic cloud and the only place it's used in the whole repo. I suspect it was carried over from the on-prem examples.

https://github.com/cognitect-labs/day-of-datomic-cloud/blob/5fc7cdee05482285dadc0a8c1fe65bc4d59dd91f/datasets/dilithium-crystals.repl#L27

**Comment by Glassonion** [comment]
Removed, thanks for catching that.
